[build]
command = "npm run build"
publish = "build/client"

[dev]
command = "npm run dev"
framework = "vite"

# Set immutable caching for static files, because they have fingerprinted filenames

[[headers]]
for = "/assets/*"
[headers.values]
"Cache-Control" = "public, max-age=31560000, immutable"

[[redirects]]
  from = "/v2/*"
  to = "/v2/:splat"
  status = 200

[[redirects]]
  from = "/(?!v2).*"
  to = "https://ambient-finance.netlify.app/:splat"
  status = 301
