
[build]
  base = "packages/frontend"
  publish = "build/client"
  command = "pnpm build"

[dev]
  command = "npm run dev"
  framework = "vite"

[[headers]]
  for = "/assets/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31560000, immutable"
