
[build]
  base = "packages/frontend"
  publish = "build/client"
  command = "node scripts/generate-announcements.js && node scripts/write-version.js && pnpm build"

[dev]
  command = "npm run dev"
  framework = "vite"

# Set immutable caching for static files, because they have fingerprinted filenames
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31560000, immutable"

[[headers]]
  for = "/version.json"
  [headers.values]
    Cache-Control = "no-store"

[[headers]]
  for = "/announcements.json"
  [headers.values]
    Cache-Control = "no-store"

# Allow blocked countries to access /blocked.html
[[redirects]]
  from = "/blocked.html"
  to = "/blocked.html"
  status = 200
  conditions = {Country = [
    "AF", # Afghanistan
    "RS", # Serbia
    "MK", # North Macedonia
    "BY", # Belarus
    "MM", # Burma
    "CF", # Central Africa Republic
    "CU", # Cuba
    "CD", # Democratic Republic of Congo
    "ET", # Ethiopia
    "IR", # Iran
    "IQ", # Iraq
    "LB", # Lebanon
    "LY", # Libya
    "ML", # Mali
    "NI", # Nicaragua
    "KP", # North Korea
    "RU", # Russia
    "SO", # Somalia
    "SS", # South Sudan
    "SD", # Sudan
    "SY", # Syria
    "VE", # Venezuela
    "YE", # Yemen
    "ZW"  # Zimbabwe
  ]}

# Redirect all other users away from /blocked and /blocked.html
[[redirects]]
  from = "/blocked*"
  to = "/"
  status = 302
  force = true

# Block all pages for specified countries
[[redirects]]
  from = "/*"
  to = "/blocked.html"
  status = 302
  force = true
  conditions = {Country = [
    "AF", # Afghanistan
    "RS", # Serbia
    "MK", # North Macedonia
    "BY", # Belarus
    "MM", # Burma
    "CF", # Central Africa Republic
    "CU", # Cuba
    "CD", # Democratic Republic of Congo
    "ET", # Ethiopia
    "IR", # Iran
    "IQ", # Iraq
    "LB", # Lebanon
    "LY", # Libya
    "ML", # Mali
    "NI", # Nicaragua
    "KP", # North Korea
    "RU", # Russia
    "SO", # Somalia
    "SS", # South Sudan
    "SD", # Sudan
    "SY", # Syria
    "VE", # Venezuela
    "YE", # Yemen
    "ZW"  # Zimbabwe
  ]}

# Redirect US traffic from primary domain to US domain, preserving the path 
[[redirects]]
  from = "https://ambi-perps.netlify.app/*"
  to = "https://ambi-perps-us.netlify.app/:splat"
  status = 302
  force = true
  conditions = { Country = ["US"] }

# Redirect non-US traffic from US domain to primary domain, preserving the path 
[[redirects]]
  from = "https://ambi-perps-us.netlify.app/*"
  to = "https://ambi-perps.netlify.app/:splat"
  status = 302
  force = true
  conditions = { Country = ["AF", "AX", "AL", "DZ", "AS", "AD", "AO", "AI", "AQ", "AG", "AR", "AM", "AW", "AU", "AT", "AZ", "BS", "BH", "BD", "BB", "BY", "BE", "BZ", "BJ", "BM", "BT", "BO", "BQ", "BA", "BW", "BV", "BR", "IO", "BN", "BG", "BF", "BI", "CV", "KH", "CM", "CA", "KY", "CF", "TD", "CL", "CN", "CX", "CC", "CO", "KM", "CD", "CG", "CK", "CR", "CI", "HR", "CU", "CW", "CY", "CZ", "DK", "DJ", "DM", "DO", "EC", "EG", "SV", "GQ", "ER", "EE", "SZ", "ET", "FK", "FO", "FJ", "FI", "FR", "GF", "PF", "TF", "GA", "GM", "GE", "DE", "GH", "GI", "GR", "GL", "GD", "GP", "GU", "GT", "GG", "GN", "GW", "GY", "HT", "HM", "VA", "HN", "HK", "HU", "IS", "IN", "ID", "IR", "IQ", "IE", "IM", "IL", "IT", "JM", "JP", "JE", "JO", "KZ", "KE", "KI", "KP", "KR", "KW", "KG", "LA", "LV", "LB", "LS", "LR", "LY", "LI", "LT", "LU", "MO", "MK", "MG", "MW", "MY", "MV", "ML", "MT", "MH", "MQ", "MR", "MU", "YT", "MX", "FM", "MD", "MC", "MN", "ME", "MS", "MA", "MZ", "MM", "NA", "NR", "NP", "NL", "NC", "NZ", "NI", "NE", "NG", "NU", "NF", "MP", "NO", "OM", "PK", "PW", "PS", "PA", "PG", "PY", "PE", "PH", "PN", "PL", "PT", "PR", "QA", "RE", "RO", "RU", "RW", "BL", "SH", "KN", "LC", "MF", "PM", "VC", "WS", "SM", "ST", "SA", "SN", "RS", "SC", "SL", "SG", "SX", "SK", "SI", "SB", "SO", "ZA", "GS", "SS", "ES", "LK", "SD", "SR", "SJ", "SE", "CH", "SY", "TW", "TJ", "TZ", "TH", "TL", "TG", "TK", "TO", "TT", "TN", "TR", "TM", "TC", "TV", "UG", "UA", "AE", "GB", "UM", "UY", "UZ", "VU", "VE", "VN", "VG", "VI", "WF", "EH", "YE", "ZM", "ZW"] }

# Main SPA redirect (must come after geofencing rules)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200