[build]
  base = "packages/frontend"
  publish = "build/client"
  command = "pnpm build"

[dev]
  command = "npm run dev"
  framework = "vite"

# Critical updates to prevent service worker caching issues
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

# Immutable caching for fingerprinted assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31560000, immutable"

# SPA redirect rule
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
