[build]
  base = "packages/frontend"
  publish = "build/client"
  command = "vite build"

[dev]
command = "npm run dev"
framework = "vite"
autoLaunch = false # Prevent SSR dev server

# Set immutable caching for static files, because they have fingerprinted filenames

[[headers]]
for = "/assets/*"
[headers.values]
"Cache-Control" = "public, max-age=31560000, immutable"
