
[build]
  base = "packages/frontend"
  publish = "build/client"
  command = "node scripts/write-version.js && pnpm build"

[dev]
  command = "npm run dev"
  framework = "vite"

# Set immutable caching for static files, because they have fingerprinted filenames
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31560000, immutable"

[[headers]]
  for = "/version.json"
  [headers.values]
    Cache-Control = "no-store"

# Allow blocked countries to access /blocked.html
[[redirects]]
  from = "/blocked.html"
  to = "/blocked.html"
  status = 200
  conditions = {Country = [
    "AF", # Afghanistan
    "RS", # Serbia
    "MK", # North Macedonia
    "BY", # Belarus
    "MM", # Burma
    "CF", # Central Africa Republic
    "CU", # Cuba
    "CD", # Democratic Republic of Congo
    "ET", # Ethiopia
    "IR", # Iran
    "IQ", # Iraq
    "LB", # Lebanon
    "LY", # Libya
    "ML", # Mali
    "NI", # Nicaragua
    "KP", # North Korea
    "RU", # Russia
    "SO", # Somalia
    "SS", # South Sudan
    "SD", # Sudan
    "SY", # Syria
    "VE", # Venezuela
    "YE", # Yemen
    "ZW"  # Zimbabwe
  ]}

# Redirect all other users away from /blocked and /blocked.html
[[redirects]]
  from = "/blocked*"
  to = "/"
  status = 302
  force = true

# Block all pages for specified countries
[[redirects]]
  from = "/*"
  to = "/blocked.html"
  status = 302
  force = true
  conditions = {Country = [
    "AF", # Afghanistan
    "RS", # Serbia
    "MK", # North Macedonia
    "BY", # Belarus
    "MM", # Burma
    "CF", # Central Africa Republic
    "CU", # Cuba
    "CD", # Democratic Republic of Congo
    "ET", # Ethiopia
    "IR", # Iran
    "IQ", # Iraq
    "LB", # Lebanon
    "LY", # Libya
    "ML", # Mali
    "NI", # Nicaragua
    "KP", # North Korea
    "RU", # Russia
    "SO", # Somalia
    "SS", # South Sudan
    "SD", # Sudan
    "SY", # Syria
    "VE", # Venezuela
    "YE", # Yemen
    "ZW"  # Zimbabwe
  ]}

# Redirect US traffic to US domain, preserving the path
[[redirects]]
  from = "/*"
  to = "https://deploy-preview-327--ambi-perps-us.netlify.app/:splat"
  status = 302
  force = true
  conditions = { Country = ["US"], Host = ["ambi-perps.netlify.app", "develop--ambi-perps.netlify.app", "deploy-preview-327--ambi-perps.netlify.app"] }

# Main SPA redirect (must come after geofencing rules)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200