[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true  # Overrides existing file matches

[build]
  base = "packages/frontend"
  publish = "build/client"
  command = "pnpm build"

[dev]
  command = "npm run dev"
  framework = "vite"

[[headers]]
  for = "/assets/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31560000, immutable"
