[build.environment]
  GIT_CONFIG_NOSYSTEM = "1"
  NETLIFY_USE_YARN = "false"
  NETLIFY_USE_PNPM = "true"

[build]
command = "git submodule deinit -f . && rm -rf .git/modules && git config --global url.\"https://raltunel:${GITHUB_TOKEN}@github.com/\".insteadOf \"https://github.com/\" && git submodule update --init --recursive && pnpm run build"
publish = "build/client"

[dev]
command = "npm run dev"
framework = "vite"

# Set immutable caching for static files, because they have fingerprinted filenames

[[headers]]
for = "/assets/*"
[headers.values]
"Cache-Control" = "public, max-age=31560000, immutable"
