[build]
  base = "packages/frontend"
  publish = "build/client"
  command = "node scripts/write-version.js && pnpm build"

[dev]
  command = "npm run dev"
  framework = "vite"

# Set immutable caching for static files, because they have fingerprinted filenames
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31560000, immutable"

[[headers]]
  for = "/version.json"
  [headers.values]
    Cache-Control = "no-store"

# Block homepage for specified countries
[[redirects]]
  from = "/"
  to = "/blocked"
  status = 301
  force = true
  conditions = {Country = ["RU", "CN", "IR"]}

# Block /index.html explicitly for specified countries
[[redirects]]
  from = "/index.html"
  to = "/blocked"
  status = 301
  force = true
  conditions = {Country = ["RU", "CN", "IR"]}

# Block all other pages for specified countries
[[redirects]]
  from = "/*"
  to = "/blocked"
  status = 301
  force = true
  conditions = {Country = ["RU", "CN", "IR"]}

# Serve the blocked page
[[redirects]]
  from = "/blocked"
  to = "/blocked.html"
  status = 200

# Main SPA redirect (must come after geofencing rules)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200