packages:
    - 'packages/*'
onlyBuiltDependencies:
    - bigint-buffer
    - blake-hash
    - bufferutil
    - esbuild
    - protobufjs
    - sharp
    - tiny-secp256k1
    - usb
    - utf-8-validate
